backup_to_json: true
convert_dates: true
restaurant: Guefen
custom_url_base: https://mycustomurl.com
custom_url_profiles: /profiles/
custom_url_reviews: /reviews/
download_images: false
download_threads: 4
headless: false
image_dir: review_images
json_path: /home/onyxia/Google-Reviews-Scraper-V2/data/guefen/guefen.json
seen_ids_path: /home/onyxia/Google-Reviews-Scraper-V2/data/guefen/guefen.ids
mongodb:
  collection: google_reviews
  database: reviews
  uri: mongodb://localhost:27017
overwrite_existing: false
preserve_original_urls: true
replace_urls: false
sort_by: relevance
stop_on_match: false
store_local_paths: true
url: https://www.google.com/maps/place/?q=place_id:ChIJwROWw8Bv5kcRb1SRKEJ4cXU&hl=en&gl=US
use_mongodb: false
